version: '3'

services:
  api:
    build: .
    command: npm run dev
    ports:
      - 8080:80
    volumes:
      - .:/server
  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - type: bind
        source: d:\IDP\Mongo\mounted_folder
        target: /data/db
